apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/storage/auth-db
  storageClassName: standard